### PR TITLE
Rename: 'addon-operators' → 'cluster-addons'

### PR DESCRIPTION
**Pull request by dholbach**
Following up on https://github.com/kubernetes/org/issues/1583 we need to update the repository name in a couple of places.

### CODE REVIEW

**Comment by atoato88** [comment]
Is it needed to rename to `cluster-addons` in `./coredns` directory?

**Comment by dholbach** [comment]
Sure, the name aliasing in Github would prevent it from failing, I just thought it'd be easier for us to move forward and use `cluster-addons` everywhere consistently now.

**Comment by stealthybox** [comment]
> Is it needed to rename to `cluster-addons` in `./coredns` directory?

+1 @dholbach can you add renames for the CoreDNS dir?

**Comment by dholbach** [comment]
Sorry. I had a couple of uncommitted changes. Fixed.

**Pull request merged**
