### PR TITLE
[Trival] beta.kubernetes.io/os and beta.kubernetes.io/arch is already deprecated since v1.14, are targeted for removal in v1.18

### PR DESCRIPTION
**Pull request by wawa0210**
fix https://github.com/kubernetes/kubernetes/issues/89477

/assign @stealthybox

### CODE REVIEW

**Comment by wawa0210** [comment]
@dholbach @johnsonj  @stealthybox

Can you take the time to help review this pr, thank you very much

**Comment by atoato88** [comment]
/lgtm

@wawa0210 Thank you for creating.

**Comment by wawa0210** [comment]
@johnsonj  @justinsb 

Can you help me take a look at this pr? Thank you very much

**Comment by johnsonj** [comment]
Thank you for porting this to the new repo and landing the change @wawa0210 

/approved

**Pull request merged**
