### PR TITLE
Update readme with some small tweaks

### PR DESCRIPTION
**Pull request by justinsb**
This is primarily checking if our tests are passing (with no code changes!)

### CODE REVIEW

**Comment by justinsb** [comment]
It does look like we need #115 :-)

**Comment by atoato88** [comment]
#115 is merged, so we can pass CI test now?

/retest

**Comment by atoato88** [comment]
@justinsb 

Prow test "pull-cluster-addons-unit-test " is passed successfully :smile:
I'll LGMT this PR, OK?

**Pull request merged**
