### PR TITLE
Update dashboard operator golden tests

### PR DESCRIPTION
**Pull request by rajansandeep**
Following https://github.com/kubernetes-sigs/cluster-addons/pull/56, the output for the golden tests has changed.

This PR fixes the output by running `HACK_AUTOFIX_EXPECTED_OUTPUT="true" go test ./...`

### CODE REVIEW

**Comment by SomtochiAma** [comment]
This looks great!

**Comment by johnsonj** [comment]
Thank you @rajansandeep ! 

I filed #62 to setup these tests as part of presubmit.

**Pull request merged**
