### PR TITLE
Move the framework for smoketests to a new test dir

### PR DESCRIPTION
**Pull request by rajansandeep**
The smoketest file previously resided in the coredns operator directory.

Moving it outside to a new "test" folder while also adding a basic framework to the existing operators

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks @rajansandeep ... will be wonderful to have more & better test coverage to keep us working with all the improvements being made here :-)

/approve
/lgtm

**Comment by rajansandeep** [comment]
@justinsb needs lgtm again due to rebase

**Comment by atoato88** [comment]
/lgtm
Thank you to update.

**Pull request merged**
