### PR TITLE
dholbach steps down

### PR DESCRIPTION
**Pull request by dholbach**
As discussed with @justinsb and @stealthybox I'm stepping down from my duties in Cluster Addons.

Thanks everyone for the great time everyone!

### CODE REVIEW

**Comment by dholbach** [comment]
Cc @stealthybox

**Comment by stealthybox** [comment]
Thank you for all of your help over the years Daniel!

**Comment by dholbach** [comment]
Does https://github.com/kubernetes-sigs/cluster-addons/actions/runs/4764233641/jobs/8468584413?pr=120 need a newer Go version?

**Comment by stealthybox** [comment]
I love that in stepping down, you are also proving a maintenance task 😅

/lgtm

**Pull request merged**
