### PR TITLE
Flannel Operator

### PR DESCRIPTION
**Pull request by SomtochiAma**

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm
Thank you to create PR :tada:
I confirmed that this operator creates flannel pods with DaemonSets.
I think that It's OK for initial implementation of flannel operator.

BTW, this includes manifest.yaml for flannel [v0.10.0](https://github.com/kubernetes-sigs/cluster-addons/blob/a0c5fc986e8085f1e8cb04d7a41e6058a5f53899/flannel/channels/packages/flannel/0.10.0/manifest.yaml#L111).
On upstream, latest flannel version is [v0.12.0](https://github.com/coreos/flannel/releases/tag/v0.12.0).
I'm not sure that should we use latest one, but where did you get manifests in your [manifest.yaml](https://github.com/kubernetes-sigs/cluster-addons/pull/69/files#diff-c9625a9f1278a47620867f72202e30db)?

**Comment by SomtochiAma** [comment]
> /lgtm
> Thank you to create PR 🎉
> I confirmed that this operator creates flannel pods with DaemonSets.
> I think that It's OK for initial implementation of flannel operator.
> 
> BTW, this includes manifest.yaml for flannel [v0.10.0](https://github.com/kubernetes-sigs/cluster-addons/blob/a0c5fc986e8085f1e8cb04d7a41e6058a5f53899/flannel/channels/packages/flannel/0.10.0/manifest.yaml#L111).
> On upstream, latest flannel version is [v0.12.0](https://github.com/coreos/flannel/releases/tag/v0.12.0).
> I'm not sure that should we use latest one, but where did you get manifests in your [manifest.yaml](https://github.com/kubernetes-sigs/cluster-addons/pull/69/files#diff-c9625a9f1278a47620867f72202e30db)?

I could include version 0.12.0 as the latest version. Wdyt?
The version 0.10.0 manifest can be found here: [https://github.com/coreos/flannel/blob/v0.10.0/Documentation/kube-flannel.yml](https://github.com/coreos/flannel/blob/v0.10.0/Documentation/kube-flannel.yml)

**Comment by atoato88** [comment]
/lgtm
Thank you to update.
I confirmed to work on both channel `stable` and `latest`.

**Comment by justinsb** [comment]
Wonderful, thanks @SomtochiAma 

/approve
/lgtm

**Pull request merged**
